from snakemake.utils import update_config

# global wildcard constraints
wildcard_constraints:
    qual="\d+",
    kvalue="\d+",
    assembler="\w+",
    sample="\w+",
    direction="\d+"

include: "config/default_datafiles.settings"
include: "config/default_workflowparams.settings"
include: "config/default_workflowconfig.settings"

include: "read_filtering/Snakefile"
include: "assembly/Snakefile"
include: "comparison/Snakefile"
include: "taxonomic_classification/Snakefile"
include: "functional_inference/Snakefile"
include: "post_processing/Snakefile"

